#lang scheme

(define FARMS '(
(farmA 100 (apricot apple blueberry))
(farmB 90 (broccoli carrot grape))
(farmC 75 (corn grape lemon))
(farmD 75 ())
(farmE 45 (lemon melon olive berry))
(farmF 70 (lemon carrot))
(farmG 50 (olive))
(farmH 150 (olive grape apple))
(farmI 50 (apple))
))

(define CUSTOMERS '(
(john (farmA farmC) (apricot lemon))
(james (farmB farmC) (grape corn))
(arya (farmB farmD) (grape broccoli))
(elenor () ())
(alan (farmG farmH) (olive apple))
(george (farmF farmE farmG) (lemon melon olive apple))
(cersei (farmE farmF farmH farmI) (lemon olive apple))
(jon (farmA farmB farmC farmD farmE farmF farmG farmH farmI) (apricot apple blueberry broccoli carrot grape corn lemon melon olive berry))
))

(define CROPS '(
(apricot farmA 10)
(apple farmA 12)
(melon farmE 22)
(olive farmE 40)
(berry farmE 10)
(lemon farmF 35)
(carrot farmF 5)
(olive farmG 60)
(olive farmH 30)
(blueberry farmA 15)
(broccoli farmB 8)
(carrot farmB 5)
(grape farmB 10)
(corn farmC 9)
(grape farmC 12)
(lemon farmC 10)
(lemon farmE 12)
(grape farmH 10)
(apple farmH 8)
(apple farmI 8)
))